__all__ = (
    'HistoryKind',
)


class HistoryKind:

    # region User

    USER_SIGN_IN_SUCCESS = 1
    USER_SIGN_IN_FAILURE = 2

    USER_REGISTER_SUCCESS = 3
    USER_REGISTER_FAILURE = 4

    USER_AUTH_RESET = 5

    USER_EDIT_SUCCESS = 6
    USER_EDIT_FAILURE = 7

    # endregion

    # region PassFile

    GET_PASSFILE_SUCCESS = 8
    GET_PASSFILE_FAILURE = 9

    CREATE_PASSFILE_SUCCESS = 10
    CREATE_PASSFILE_FAILURE = 11

    EDIT_PASSFILE_INFO_SUCCESS = 12
    EDIT_PASSFILE_INFO_FAILURE = 13

    EDIT_PASSFILE_SMTH_SUCCESS = 14
    EDIT_PASSFILE_SMTH_FAILURE = 15

    DELETE_PASSFILE_SUCCESS = 16
    DELETE_PASSFILE_FAILURE = 17

    # endregion
