__all__ = (
    'HistoryKind',
)


class HistoryKind:

    # region User

    USER_SIGN_IN_SUCCESS = 1
    USER_SIGN_IN_FAILURE = 2

    USER_SIGN_UP_SUCCESS = 3
    USER_SIGN_UP_FAILURE = 4

    USER_SESSIONS_RESET = 5

    USER_EDIT_SUCCESS = 6
    USER_EDIT_FAILURE = 7

    # endregion

    # region PassFile
    
    GET_PASSFILE_LIST_SUCCESS = 8
    GET_PASSFILE_LIST_FAILURE = 9

    GET_PASSFILE_INFO_SUCCESS = 10
    GET_PASSFILE_INFO_FAILURE = 11

    GET_PASSFILE_SMTH_SUCCESS = 12
    GET_PASSFILE_SMTH_FAILURE = 13

    CREATE_PASSFILE_SUCCESS = 14
    CREATE_PASSFILE_FAILURE = 15

    EDIT_PASSFILE_INFO_SUCCESS = 16
    EDIT_PASSFILE_INFO_FAILURE = 17

    EDIT_PASSFILE_SMTH_SUCCESS = 18
    EDIT_PASSFILE_SMTH_FAILURE = 19

    DELETE_PASSFILE_SUCCESS = 20
    DELETE_PASSFILE_FAILURE = 21

    # endregion
